# EPL Match Outcome Prediction

## Overview
This project explores 3 seasons (2022-2025) of English Premier League match data 
to find patterns in team performance and build a model predicting match outcomes 
(Home Win / Draw / Away Win).

## Key Findings
- Home advantage is real: home teams won ~150 more matches than away teams over 
  the period studied.
- Home advantage varies massively by team quality — e.g., Man City won ~77% of 
  home games vs Ipswich's ~6%. Team strength matters far more than venue alone.
- Team quality is consistent across home/away: the same strong teams dominate 
  regardless of venue.
- Shots on target strongly correlates with winning — winning teams average 
  ~3 more shots on target than their opponents.
- Cards/discipline has only a weak relationship with match outcomes.

## Model
A Logistic Regression model was trained on pre-match features (rolling recent 
form, goals scored/conceded, and form similarity between teams) to predict match 
outcomes.

- **Accuracy: 51.4%** (baseline of always predicting "Home Win" = 46.8%)
- The model reliably predicts home wins and away wins, but **fails to predict 
  draws entirely** — a known, documented challenge in soccer analytics, since 
  draws lack a distinct statistical signature compared to decisive results.

## Limitations & Next Steps
- Draw prediction remains an open problem; could explore different model types 
  (e.g. Random Forest) or additional features like head-to-head history.
- Only 3 seasons of data were used to avoid outdated patterns from older seasons.

In [65]:
import pandas as pd

In [66]:
df = pd.read_csv('epl_final.csv')

In [67]:
pd.read_csv(r'C:\Users\nazza\Downloads\Data Science Projects\archive\epl_final.csv')

,Season,MatchDate,HomeTeam,AwayTeam,FullTimeHomeGoals,FullTimeAwayGoals,FullTimeResult,HalfTimeHomeGoals,HalfTimeAwayGoals,HalfTimeResult,...,HomeShotsOnTarget,AwayShotsOnTarget,HomeCorners,AwayCorners,HomeFouls,AwayFouls,HomeYellowCards,AwayYellowCards,HomeRedCards,AwayRedCards
0,2000/01,2000-08-19,Charlton,Man City,4,0,H,2,0,H,...,14,4,6,6,13,12,1,2,0,0
1,2000/01,2000-08-19,Chelsea,West Ham,4,2,H,1,0,H,...,10,5,7,7,19,14,1,2,0,0
2,2000/01,2000-08-19,Coventry,Middlesbrough,1,3,A,1,1,D,...,3,9,8,4,15,21,5,3,1,0
3,2000/01,2000-08-19,Derby,Southampton,2,2,D,1,2,A,...,4,6,5,8,11,13,1,1,0,0
4,2000/01,2000-08-19,Leeds,Everton,2,0,H,2,0,H,...,8,6,6,4,21,20,1,3,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9375,2024/25,2025-05-04,Brentford,Man United,4,3,H,2,1,H,...,6,5,7,4,8,10,0,2,0,0
9376,2024/25,2025-05-04,Brighton,Newcastle,1,1,D,1,0,H,...,2,5,1,4,15,10,2,1,0,0
9377,2024/25,2025-05-04,West Ham,Tottenham,1,1,D,1,1,D,...,2,2,1,3,18,15,2,2,0,0
9378,2024/25,2025-05-04,Chelsea,Liverpool,3,1,H,1,0,H,...,7,2,3,6,10,11,2,2,0,0
9379,2024/25,2025-05-05,Crystal Palace,Nott'm Forest,1,1,D,0,0,D,...,3,4,7,4,9,15,3,8,0,0

In [68]:
df.head()

,Season,MatchDate,HomeTeam,AwayTeam,FullTimeHomeGoals,FullTimeAwayGoals,FullTimeResult,HalfTimeHomeGoals,HalfTimeAwayGoals,HalfTimeResult,...,HomeShotsOnTarget,AwayShotsOnTarget,HomeCorners,AwayCorners,HomeFouls,AwayFouls,HomeYellowCards,AwayYellowCards,HomeRedCards,AwayRedCards
0,2000/01,2000-08-19,Charlton,Man City,4,0,H,2,0,H,...,14,4,6,6,13,12,1,2,0,0
1,2000/01,2000-08-19,Chelsea,West Ham,4,2,H,1,0,H,...,10,5,7,7,19,14,1,2,0,0
2,2000/01,2000-08-19,Coventry,Middlesbrough,1,3,A,1,1,D,...,3,9,8,4,15,21,5,3,1,0
3,2000/01,2000-08-19,Derby,Southampton,2,2,D,1,2,A,...,4,6,5,8,11,13,1,1,0,0
4,2000/01,2000-08-19,Leeds,Everton,2,0,H,2,0,H,...,8,6,6,4,21,20,1,3,0,0

In [69]:
df['Season'].unique()

<StringArray>
['2000/01', '2001/02', '2002/03', '2003/04', '2004/05', '2005/06', '2006/07',
 '2007/08', '2008/09', '2009/10', '2010/11', '2011/12', '2012/13', '2013/14',
 '2014/15', '2015/16', '2016/17', '2017/18', '2018/19', '2019/20', '2020/21',
 '2021/22', '2022/23', '2023/24', '2024/25']
Length: 25, dtype: str

In [70]:
df = df[df['Season'].isin(['2024/25', '2023/24', '2022/23'])]

In [71]:
df.head()

,Season,MatchDate,HomeTeam,AwayTeam,FullTimeHomeGoals,FullTimeAwayGoals,FullTimeResult,HalfTimeHomeGoals,HalfTimeAwayGoals,HalfTimeResult,...,HomeShotsOnTarget,AwayShotsOnTarget,HomeCorners,AwayCorners,HomeFouls,AwayFouls,HomeYellowCards,AwayYellowCards,HomeRedCards,AwayRedCards
8270,2022/23,2022-08-05,Crystal Palace,Arsenal,0,2,A,0,1,A,...,2,2,3,5,16,11,1,2,0,0
8271,2022/23,2022-08-06,Fulham,Liverpool,2,2,D,1,0,H,...,3,4,4,4,7,9,2,0,0,0
8272,2022/23,2022-08-06,Bournemouth,Aston Villa,2,0,H,1,0,H,...,3,2,5,5,18,16,3,3,0,0
8273,2022/23,2022-08-06,Leeds,Wolves,2,1,H,1,1,D,...,4,6,6,4,13,9,2,0,0,0
8274,2022/23,2022-08-06,Newcastle,Nott'm Forest,2,0,H,0,0,D,...,10,0,11,1,9,14,0,3,0,0

In [72]:
df.shape

(1110, 22)

In [73]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1110 entries, 8270 to 9379
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Season             1110 non-null   str
 1   MatchDate          1110 non-null   str
 2   HomeTeam           1110 non-null   str
 3   AwayTeam           1110 non-null   str
 4   FullTimeHomeGoals  1110 non-null   int64
 5   FullTimeAwayGoals  1110 non-null   int64
 6   FullTimeResult     1110 non-null   str
 7   HalfTimeHomeGoals  1110 non-null   int64
 8   HalfTimeAwayGoals  1110 non-null   int64
 9   HalfTimeResult     1110 non-null   str
 10  HomeShots          1110 non-null   int64
 11  AwayShots          1110 non-null   int64
 12  HomeShotsOnTarget  1110 non-null   int64
 13  AwayShotsOnTarget  1110 non-null   int64
 14  HomeCorners        1110 non-null   int64
 15  AwayCorners        1110 non-null   int64
 16  HomeFouls          1110 non-null   int64
 17  AwayFouls          1110 non-null   int64
 18  HomeYellowCards    1110 non-null   int64
 19  AwayYellowCards    1110 non-null   int64
 20  HomeRedCards       1110 non-null   int64
 21  AwayRedCards       1110 non-null   int64
dtypes: int64(16), str(6)
memory usage: 190.9 KB

In [74]:
df['MatchDate'] = pd.to_datetime(df['MatchDate'])

In [75]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1110 entries, 8270 to 9379
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Season             1110 non-null   str
 1   MatchDate          1110 non-null   datetime64[us]
 2   HomeTeam           1110 non-null   str
 3   AwayTeam           1110 non-null   str
 4   FullTimeHomeGoals  1110 non-null   int64
 5   FullTimeAwayGoals  1110 non-null   int64
 6   FullTimeResult     1110 non-null   str
 7   HalfTimeHomeGoals  1110 non-null   int64
 8   HalfTimeAwayGoals  1110 non-null   int64
 9   HalfTimeResult     1110 non-null   str
 10  HomeShots          1110 non-null   int64
 11  AwayShots          1110 non-null   int64
 12  HomeShotsOnTarget  1110 non-null   int64
 13  AwayShotsOnTarget  1110 non-null   int64
 14  HomeCorners        1110 non-null   int64
 15  AwayCorners        1110 non-null   int64
 16  HomeFouls          1110 non-null   int64
 17  AwayFouls          1110 non-null   int64
 18  HomeYellowCards    1110 non-null   int64
 19  AwayYellowCards    1110 non-null   int64
 20  HomeRedCards       1110 non-null   int64
 21  AwayRedCards       1110 non-null   int64
dtypes: datetime64[us](1), int64(16), str(5)
memory usage: 190.9 KB

In [76]:
df['FullTimeResult'].value_counts()

FullTimeResult
H    503
A    350
D    257
Name: count, dtype: int64

In [77]:
df.groupby('HomeTeam')['FullTimeResult'].value_counts(normalize=True)

HomeTeam     FullTimeResult
Arsenal      H                 0.696429
             D                 0.196429
             A                 0.107143
Aston Villa  H                 0.607143
             D                 0.232143
                                 ...
West Ham     A                 0.339286
             D                 0.303571
Wolves       A                 0.436364
             H                 0.418182
             D                 0.145455
Name: proportion, Length: 72, dtype: float64

In [78]:
(df[df['FullTimeResult'] == 'H'].groupby('HomeTeam').size() / df.groupby('HomeTeam').size()).sort_values(ascending=False)

HomeTeam
Man City            0.767857
Liverpool           0.763636
Arsenal             0.696429
Newcastle           0.618182
Aston Villa         0.607143
Man United          0.563636
Tottenham           0.563636
Chelsea             0.500000
Brighton            0.446429
Fulham              0.436364
Brentford           0.428571
Wolves              0.418182
Nott'm Forest       0.400000
Bournemouth         0.363636
West Ham            0.357143
Crystal Palace      0.357143
Everton             0.321429
Leeds               0.263158
Leicester           0.216216
Luton               0.210526
Burnley             0.105263
Sheffield United    0.105263
Southampton         0.083333
Ipswich             0.058824
dtype: float64

In [79]:
(df[df['FullTimeResult'] == 'A'].groupby('HomeTeam').size() / df.groupby('HomeTeam').size()).sort_values(ascending=False)

HomeTeam
Southampton         0.722222
Ipswich             0.705882
Burnley             0.684211
Sheffield United    0.684211
Leicester           0.594595
Luton               0.578947
Wolves              0.436364
Everton             0.392857
Bournemouth         0.381818
Leeds               0.368421
Tottenham           0.363636
Fulham              0.345455
West Ham            0.339286
Nott'm Forest       0.327273
Crystal Palace      0.321429
Man United          0.272727
Brentford           0.250000
Brighton            0.232143
Chelsea             0.214286
Newcastle           0.163636
Aston Villa         0.160714
Arsenal             0.107143
Man City            0.071429
Liverpool           0.054545
dtype: float64

In [80]:
(df[df['FullTimeResult'] == 'A'].groupby('AwayTeam').size() / df.groupby('AwayTeam').size()).sort_values(ascending=False)

AwayTeam
Arsenal             0.600000
Man City            0.581818
Liverpool           0.464286
Newcastle           0.392857
Aston Villa         0.381818
Man United          0.357143
Chelsea             0.345455
Brighton            0.327273
Fulham              0.321429
Tottenham           0.321429
Bournemouth         0.321429
Brentford           0.290909
Crystal Palace      0.272727
West Ham            0.254545
Nott'm Forest       0.250000
Wolves              0.232143
Everton             0.200000
Ipswich             0.166667
Leicester           0.166667
Burnley             0.157895
Southampton         0.135135
Leeds               0.105263
Luton               0.105263
Sheffield United    0.052632
dtype: float64

In [81]:
df.groupby('HomeTeam')[['FullTimeHomeGoals']].mean().sort_values('FullTimeHomeGoals', ascending=False)

                  FullTimeHomeGoals
HomeTeam
Man City                   2.696429
Liverpool                  2.436364
Arsenal                    2.410714
Newcastle                  2.236364
Aston Villa                2.017857
Tottenham                  1.981818
Brentford                  1.821429
Chelsea                    1.750000
Brighton                   1.678571
Fulham                     1.600000
Man United                 1.600000
Luton                      1.473684
Nott'm Forest              1.418182
West Ham                   1.410714
Crystal Palace             1.392857
Leeds                      1.368421
Wolves                     1.290909
Bournemouth                1.236364
Everton                    1.107143
Burnley                    1.000000
Sheffield United           1.000000
Leicester                  0.972973
Southampton                0.861111
Ipswich                    0.764706

In [82]:
df['ShotAccuracyDiff'] = df['HomeShotsOnTarget'] - df['AwayShotsOnTarget']
df.groupby('FullTimeResult')['ShotAccuracyDiff'].mean()

FullTimeResult
A   -1.857143
D    0.486381
H    2.978131
Name: ShotAccuracyDiff, dtype: float64

In [83]:
df['CardDiff'] = df['HomeYellowCards'] + df['HomeRedCards']*2 - (df['AwayYellowCards'] + df['AwayRedCards']*2)
df.groupby('FullTimeResult')['CardDiff'].mean()

FullTimeResult
A    0.054286
D   -0.295720
H   -0.491054
Name: CardDiff, dtype: float64

In [84]:
df = df.sort_values('MatchDate').reset_index(drop=True)

In [85]:
home_games = df[['MatchDate', 'HomeTeam', 'FullTimeHomeGoals', 'FullTimeAwayGoals', 'FullTimeResult']].copy()
home_games.columns = ['MatchDate', 'Team', 'GoalsFor', 'GoalsAgainst', 'Result']
home_games['Points'] = home_games['Result'].map({'H': 3, 'D': 1, 'A': 0})

away_games = df[['MatchDate', 'AwayTeam', 'FullTimeAwayGoals', 'FullTimeHomeGoals', 'FullTimeResult']].copy()
away_games.columns = ['MatchDate', 'Team', 'GoalsFor', 'GoalsAgainst', 'Result']
away_games['Points'] = away_games['Result'].map({'H': 0, 'D': 1, 'A': 3})

team_games = pd.concat([home_games, away_games]).sort_values(['Team', 'MatchDate']).reset_index(drop=True)

In [86]:
team_games.head(10)

   MatchDate     Team  GoalsFor  GoalsAgainst Result  Points
0 2022-08-05  Arsenal         2             0      A       3
1 2022-08-13  Arsenal         4             2      H       3
2 2022-08-20  Arsenal         3             0      A       3
3 2022-08-27  Arsenal         2             1      H       3
4 2022-08-31  Arsenal         2             1      H       3
5 2022-09-04  Arsenal         1             3      H       0
6 2022-09-18  Arsenal         3             0      A       3
7 2022-10-01  Arsenal         3             1      H       3
8 2022-10-09  Arsenal         3             2      H       3
9 2022-10-16  Arsenal         1             0      A       3

In [87]:
team_games['Form_Last5'] = team_games.groupby('Team')['Points'].transform(lambda x: x.shift(1).rolling(5, min_periods=1).mean())

In [88]:
team_games[team_games['Team'] == 'Arsenal'].head(10)

   MatchDate     Team  GoalsFor  GoalsAgainst Result  Points  Form_Last5
0 2022-08-05  Arsenal         2             0      A       3         NaN
1 2022-08-13  Arsenal         4             2      H       3         3.0
2 2022-08-20  Arsenal         3             0      A       3         3.0
3 2022-08-27  Arsenal         2             1      H       3         3.0
4 2022-08-31  Arsenal         2             1      H       3         3.0
5 2022-09-04  Arsenal         1             3      H       0         3.0
6 2022-09-18  Arsenal         3             0      A       3         2.4
7 2022-10-01  Arsenal         3             1      H       3         2.4
8 2022-10-09  Arsenal         3             2      H       3         2.4
9 2022-10-16  Arsenal         1             0      A       3         2.4

In [89]:
df = df.merge(
    team_games[['MatchDate', 'Team', 'Form_Last5']],
    left_on=['MatchDate', 'HomeTeam'],
    right_on=['MatchDate', 'Team'],
    how='left'
).rename(columns={'Form_Last5': 'HomeForm'}).drop(columns='Team')

In [90]:
df = df.merge(
    team_games[['MatchDate', 'Team', 'Form_Last5']],
    left_on=['MatchDate', 'AwayTeam'],
    right_on=['MatchDate', 'Team'],
    how='left'
).rename(columns={'Form_Last5': 'AwayForm'}).drop(columns='Team')

In [91]:
df[['MatchDate', 'HomeTeam', 'AwayTeam', 'HomeForm', 'AwayForm']].head(10)

   MatchDate        HomeTeam       AwayTeam  HomeForm  AwayForm
0 2022-08-05  Crystal Palace        Arsenal       NaN       NaN
1 2022-08-06          Fulham      Liverpool       NaN       NaN
2 2022-08-06     Bournemouth    Aston Villa       NaN       NaN
3 2022-08-06           Leeds         Wolves       NaN       NaN
4 2022-08-06       Newcastle  Nott'm Forest       NaN       NaN
5 2022-08-06       Tottenham    Southampton       NaN       NaN
6 2022-08-06         Everton        Chelsea       NaN       NaN
7 2022-08-07       Leicester      Brentford       NaN       NaN
8 2022-08-07      Man United       Brighton       NaN       NaN
9 2022-08-07        West Ham       Man City       NaN       NaN

In [92]:
df[['MatchDate', 'HomeTeam', 'AwayTeam', 'HomeForm', 'AwayForm']].iloc[50:60]

    MatchDate       HomeTeam        AwayTeam  HomeForm  AwayForm
50 2022-09-03      Brentford           Leeds       1.2       1.6
51 2022-09-03         Wolves     Southampton       0.6       1.4
52 2022-09-03    Aston Villa        Man City       0.6       2.6
53 2022-09-03      Tottenham          Fulham       2.2       1.6
54 2022-09-03        Everton       Liverpool       0.6       1.6
55 2022-09-03      Newcastle  Crystal Palace       1.2       1.0
56 2022-09-03        Chelsea        West Ham       1.4       0.8
57 2022-09-03  Nott'm Forest     Bournemouth       0.8       0.8
58 2022-09-04       Brighton       Leicester       2.0       0.2
59 2022-09-04     Man United         Arsenal       1.8       3.0

In [93]:
team_games['AvgGoalsFor_Last5'] = team_games.groupby('Team')['GoalsFor'].transform(lambda x: x.shift(1).rolling(5, min_periods=1).mean())
team_games['AvgGoalsAgainst_Last5'] = team_games.groupby('Team')['GoalsAgainst'].transform(lambda x: x.shift(1).rolling(5, min_periods=1).mean())

In [94]:
df.head(5)

,Season,MatchDate,HomeTeam,AwayTeam,FullTimeHomeGoals,FullTimeAwayGoals,FullTimeResult,HalfTimeHomeGoals,HalfTimeAwayGoals,HalfTimeResult,...,HomeFouls,AwayFouls,HomeYellowCards,AwayYellowCards,HomeRedCards,AwayRedCards,ShotAccuracyDiff,CardDiff,HomeForm,AwayForm
0,2022/23,2022-08-05,Crystal Palace,Arsenal,0,2,A,0,1,A,...,16,11,1,2,0,0,0,-1,NaN,NaN
1,2022/23,2022-08-06,Fulham,Liverpool,2,2,D,1,0,H,...,7,9,2,0,0,0,-1,2,NaN,NaN
2,2022/23,2022-08-06,Bournemouth,Aston Villa,2,0,H,1,0,H,...,18,16,3,3,0,0,1,0,NaN,NaN
3,2022/23,2022-08-06,Leeds,Wolves,2,1,H,1,1,D,...,13,9,2,0,0,0,-2,2,NaN,NaN
4,2022/23,2022-08-06,Newcastle,Nott'm Forest,2,0,H,0,0,D,...,9,14,0,3,0,0,10,-3,NaN,NaN

In [95]:
team_games.head(5)

,MatchDate,Team,GoalsFor,GoalsAgainst,Result,Points,Form_Last5,AvgGoalsFor_Last5,AvgGoalsAgainst_Last5
0,2022-08-05,Arsenal,2,0,A,3,NaN,NaN,NaN
1,2022-08-13,Arsenal,4,2,H,3,3.0,2.00,0.000000
2,2022-08-20,Arsenal,3,0,A,3,3.0,3.00,1.000000
3,2022-08-27,Arsenal,2,1,H,3,3.0,3.00,0.666667
4,2022-08-31,Arsenal,2,1,H,3,3.0,2.75,0.750000

In [96]:
df = df.merge(
    team_games[['AvgGoalsFor_Last5', 'MatchDate', 'Team']],
    left_on=['MatchDate', 'HomeTeam'],
    right_on=['MatchDate', 'Team'],
    how = 'left'
               
).rename(columns={'AvgGoalsFor_Last5': 'HomeAvgGoalsFor'}).drop(columns='Team')

In [97]:
df = df.merge(
    team_games[['MatchDate', 'Team', 'AvgGoalsFor_Last5']],
    left_on=['MatchDate', 'AwayTeam'],
    right_on=['MatchDate', 'Team'],
    how = 'left'
).rename(columns={'AvgGoalsFor_Last5': 'AwayAvgGoalsFor'}).drop(columns='Team'  )

In [98]:
df = df.merge(
    team_games[['MatchDate', 'Team', 'AvgGoalsAgainst_Last5']],
    left_on=['MatchDate', 'HomeTeam'],
    right_on=['MatchDate', 'Team'],
    how='left'
).rename(columns={'AvgGoalsAgainst_Last5': 'HomeAvgGoalsAgainst'}).drop(columns='Team' )

In [99]:
df = df.merge(
    team_games[['MatchDate', 'Team', 'AvgGoalsAgainst_Last5']],
    left_on=['MatchDate', 'AwayTeam'],
    right_on=['MatchDate', 'Team'],
    how='left'
).rename(columns={'AvgGoalsAgainst_Last5': 'AwayAvgGoalsAgainst'}).drop(columns='Team'  )

In [100]:
df[['MatchDate', 'HomeTeam', 'AwayTeam', 'HomeAvgGoalsFor', 'AwayAvgGoalsFor', 'HomeAvgGoalsAgainst', 'AwayAvgGoalsAgainst']].iloc[50:60]

,MatchDate,HomeTeam,AwayTeam,HomeAvgGoalsFor,AwayAvgGoalsFor,HomeAvgGoalsAgainst,AwayAvgGoalsAgainst
50,2022-09-03,Brentford,Leeds,2.0,1.6,1.4,1.0
51,2022-09-03,Wolves,Southampton,0.4,1.4,0.8,1.8
52,2022-09-03,Aston Villa,Man City,0.8,3.8,1.8,1.0
53,2022-09-03,Tottenham,Fulham,2.0,1.6,0.8,1.4
54,2022-09-03,Everton,Liverpool,0.8,3.0,1.2,1.2
55,2022-09-03,Newcastle,Crystal Palace,1.4,1.4,1.2,1.8
56,2022-09-03,Chelsea,West Ham,1.2,0.4,1.6,1.2
57,2022-09-03,Nott'm Forest,Bournemouth,0.4,0.4,2.2,3.2
58,2022-09-04,Brighton,Leicester,1.2,1.2,0.6,2.2
59,2022-09-04,Man United,Arsenal,1.0,2.6,1.4,0.8

In [101]:
df.head()

,Season,MatchDate,HomeTeam,AwayTeam,FullTimeHomeGoals,FullTimeAwayGoals,FullTimeResult,HalfTimeHomeGoals,HalfTimeAwayGoals,HalfTimeResult,...,HomeRedCards,AwayRedCards,ShotAccuracyDiff,CardDiff,HomeForm,AwayForm,HomeAvgGoalsFor,AwayAvgGoalsFor,HomeAvgGoalsAgainst,AwayAvgGoalsAgainst
0,2022/23,2022-08-05,Crystal Palace,Arsenal,0,2,A,0,1,A,...,0,0,0,-1,NaN,NaN,NaN,NaN,NaN,NaN
1,2022/23,2022-08-06,Fulham,Liverpool,2,2,D,1,0,H,...,0,0,-1,2,NaN,NaN,NaN,NaN,NaN,NaN
2,2022/23,2022-08-06,Bournemouth,Aston Villa,2,0,H,1,0,H,...,0,0,1,0,NaN,NaN,NaN,NaN,NaN,NaN
3,2022/23,2022-08-06,Leeds,Wolves,2,1,H,1,1,D,...,0,0,-2,2,NaN,NaN,NaN,NaN,NaN,NaN
4,2022/23,2022-08-06,Newcastle,Nott'm Forest,2,0,H,0,0,D,...,0,0,10,-3,NaN,NaN,NaN,NaN,NaN,NaN

In [102]:
df = df.dropna(subset=['HomeForm', 'AwayForm', 'HomeAvgGoalsFor', 'AwayAvgGoalsFor', 'HomeAvgGoalsAgainst', 'AwayAvgGoalsAgainst'])
print(df.shape)

(1096, 30)

In [103]:
df.head()

,Season,MatchDate,HomeTeam,AwayTeam,FullTimeHomeGoals,FullTimeAwayGoals,FullTimeResult,HalfTimeHomeGoals,HalfTimeAwayGoals,HalfTimeResult,...,HomeRedCards,AwayRedCards,ShotAccuracyDiff,CardDiff,HomeForm,AwayForm,HomeAvgGoalsFor,AwayAvgGoalsFor,HomeAvgGoalsAgainst,AwayAvgGoalsAgainst
10,2022/23,2022-08-13,Wolves,Fulham,0,0,D,0,0,D,...,0,0,-2,0,0.0,1.0,1.0,2.0,2.0,2.0
11,2022/23,2022-08-13,Southampton,Leeds,2,2,D,0,0,D,...,0,0,-1,-2,0.0,3.0,1.0,2.0,4.0,1.0
12,2022/23,2022-08-13,Man City,Bournemouth,4,0,H,3,0,H,...,0,0,6,-3,3.0,3.0,2.0,2.0,0.0,0.0
13,2022/23,2022-08-13,Brentford,Man United,4,0,H,4,0,H,...,0,0,3,-4,1.0,0.0,2.0,1.0,2.0,2.0
14,2022/23,2022-08-13,Arsenal,Leicester,4,2,H,2,0,H,...,0,0,5,0,3.0,1.0,2.0,2.0,0.0,2.0

In [104]:
features = ['HomeForm', 'AwayForm', 'HomeAvgGoalsFor', 'AwayAvgGoalsFor', 'HomeAvgGoalsAgainst', 'AwayAvgGoalsAgainst']
X = df[features]
y = df['FullTimeResult']

In [105]:
X.head()

,HomeForm,AwayForm,HomeAvgGoalsFor,AwayAvgGoalsFor,HomeAvgGoalsAgainst,AwayAvgGoalsAgainst
10,0.0,1.0,1.0,2.0,2.0,2.0
11,0.0,3.0,1.0,2.0,4.0,1.0
12,3.0,3.0,2.0,2.0,0.0,0.0
13,1.0,0.0,2.0,1.0,2.0,2.0
14,3.0,1.0,2.0,2.0,0.0,2.0

In [106]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [107]:
print(X_train.shape, X_test.shape)

(876, 6) (220, 6)

In [108]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [109]:
from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test)
accuracy_score(y_test, y_pred)

0.4954545454545455

In [110]:
y_test.value_counts(normalize=True)

FullTimeResult
H    0.468182
A    0.290909
D    0.240909
Name: proportion, dtype: float64

In [111]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           A       0.38      0.56      0.46        64
           D       0.00      0.00      0.00        53
           H       0.58      0.71      0.64       103

    accuracy                           0.50       220
   macro avg       0.32      0.42      0.36       220
weighted avg       0.38      0.50      0.43       220

c:\Users\nazza\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\nazza\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\nazza\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [112]:
df['FormDiff'] = abs(df['HomeForm'] - df['AwayForm'])
df['GoalDiffForm'] = abs(df['HomeAvgGoalsFor'] - df['AwayAvgGoalsFor'])

In [113]:
features = ['HomeForm', 'AwayForm', 'HomeAvgGoalsFor', 'AwayAvgGoalsFor', 'HomeAvgGoalsAgainst', 'AwayAvgGoalsAgainst', 'FormDiff', 'GoalDiffForm']
X = df[features]
y = df['FullTimeResult']

In [114]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [115]:
model = LogisticRegression(max_iter=1000) 
model.fit(X_train, y_train) 
y_pred = model.predict(X_test)

In [116]:
print(accuracy_score(y_test, y_pred))

0.5136363636363637

In [117]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           A       0.41      0.56      0.47        64
           D       0.00      0.00      0.00        53
           H       0.58      0.75      0.66       103

    accuracy                           0.51       220
   macro avg       0.33      0.44      0.38       220
weighted avg       0.39      0.51      0.44       220

c:\Users\nazza\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\nazza\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\nazza\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])